default:
    trainer: ppo
    batch_size: 1000
    beta: 1.0e-2
    buffer_size: 10000
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 256
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 3e5
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 3
    time_horizon: 128
    sequence_length: 64
    summary_freq: 2000
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128

